return {
  -- {
  --   'williamboman/mason.nvim',
  --   opts = function(_, opts)
  --     table.insert(opts.ensure_installed, 'mypy')
  --   end,
  -- },
  -- {
  --   'jose-elias-alvarez/null-ls.nvim',
  --   opts = function(_, opts)
  --     local nls = require('null-ls')
  --     table.insert(
  --       opts.sources,
  --       nls.builtins.diagnostics.mypy.with({
  --         extra_args = {
  --           '--ignore-missing-imports',
  --         },
  --       })
  --     )
  --   end,
  -- },
}
